services:
  auth:
    build:
      context: ./srcs/auth
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_REFRESH_SECRET=your_jwt_refresh_secret_key_here
    env_file:
      - ./srcs/auth/.env
    networks:
      - transcendence_network

  api-gateway:
    build:
      context: ./srcs/api_gateway
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - auth
      - relay
    networks:
      - transcendence_network
#    restart: on-failure

  frontend:
    build:
      context: ./srcs/frontend
      dockerfile: Dockerfile
    networks:
      - transcendence_network

  web-nginx:
    build:
      context: ./srcs/web_nginx
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - frontend
    networks:
      - transcendence_network

  engine:
    build:
      context: ./srcs/game/engine
      dockerfile: Dockerfile
    container_name: pong_engine
    depends_on:
      - frontend
    networks:
      - transcendence_network

  relay:
    build:
      context: ./srcs/game/relay
      dockerfile: Dockerfile
    container_name: pong_relay
    depends_on:
      - engine
    networks:
    - transcendence_network

networks:
  transcendence_network:
    driver: bridge