networks:
  transcendence_network:
    driver: bridge

services:
  vault:
    build:
      context: .
    container_name: vault
    cap_add:
      - IPC_LOCK
    ports: []
    volumes:
      - transcendence_vault_data:/vault/data
    command: vault server -config=/vault/config/vault.hcl
    env_file:
      - .env
    networks:
      - transcendence_network

  database:
    build:
      context: ./srcs/database
      dockerfile: Dockerfile
    image: database
    volumes:
      - transcendence_database_data:/data 
    dns:
      - 8.8.8.8
      - 1.1.1.1
    env_file:
      - .env
    networks:
      - transcendence_network

  auth:
    build:
      context: ./srcs/auth
      dockerfile: Dockerfile
    image: auth
    dns:
      - 8.8.8.8
      - 1.1.1.1
    env_file:
      - .env
    networks:
      - transcendence_network
    
  game-history:
    build:
      context: ./srcs/game_history
      dockerfile: Dockerfile
    image: game-history
    dns:
      - 8.8.8.8
      - 1.1.1.1
    env_file:
      - .env
    networks:
      - transcendence_network

  api-gateway:
    build:
      context: ./srcs/api_gateway
      dockerfile: Dockerfile
    image: api-gateway
    ports:
      - "8443:443"
      - "8081:80"
    depends_on:
      - auth
      - relay
    networks:
      - transcendence_network

  frontend:
    build:
      context: ./srcs/frontend
      dockerfile: Dockerfile
    image: frontend
    dns:
      - 8.8.8.8
      - 1.1.1.1
    networks:
      - transcendence_network

  web-nginx:
    build:
      context: ./srcs/web_nginx
      dockerfile: Dockerfile
    image: web-nginx
    ports:
      - "8080:8080"
    depends_on:
      - frontend
    networks:
      - transcendence_network

  engine:
    build:
      context: ./srcs/game/engine
      dockerfile: Dockerfile
    image: engine
    depends_on:
      - frontend
    networks:
      - transcendence_network

  relay:
    build:
      context: ./srcs/game/relay
      dockerfile: Dockerfile
      args:
        GAME_HISTORY_SERVICE_URL: ${GAME_HISTORY_SERVICE_URL} 
    image: relay
    depends_on:
      - engine
      - game-history
    env_file:
      .env
    networks:
      - transcendence_network

volumes:
  transcendence_database_data:
    external: true
  transcendence_vault_data:
    external: true
