version: '3.8'

services:
  auth:
    build:
      context: ./srcs/auth
      dockerfile: Dockerfile
    volumes:
      - ./srcs/auth:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_REFRESH_SECRET=your_jwt_refresh_secret_key_here
    networks:
      - transcendence_network

  api-gateway:
    build:
      context: ./srcs/api_gateway
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - auth
      - frontend
    networks:
      - transcendence_network

  frontend:
    build:
      context: ./srcs/frontend
      dockerfile: Dockerfile
    networks:
      - transcendence_network

networks:
  transcendence_network:
    driver: bridge