version: '3.8'

services:
  auth:
    build:
      context: ./srcs/auth
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./srcs/auth:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_REFRESH_SECRET=your_jwt_refresh_secret_key_here
    networks:
      - transcendence_network

networks:
  transcendence_network:
    driver: bridge
