version: '3.8'

services:

  vault:
    image: hashicorp/vault:1.16
    container_name: vault
    environment:
      # Modo dev – NUNCA usar em produção!
      VAULT_DEV_ROOT_TOKEN_ID: my-root-token
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:            # evita que o Vault seja swapado em disco
      - IPC_LOCK
    ports:
      - "8200:8200"     # UI / API do Vault
    networks:
      - transcendence_network

  api:
    build: ./srcs/vault
    container_name: fastify-api
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: my-root-token
      PORT: 3001
    depends_on:
      - vault
    ports:
      - "3001:3001"
    networks:
      - transcendence_network

  database:
    build:
      context: ./srcs/database
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./srcs/database:/app
      - ./data:/app/data
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=5000
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_REFRESH_SECRET=your_jwt_refresh_secret_key_here
    # env_file:
    #   - ./srcs/database/.env
    networks:
      - transcendence_network 
  auth:
    build:
      context: ./srcs/auth
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./srcs/auth:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DATABASE_URL=http://database:5000
      - JWT_SECRET=your_jwt_secret_key_here
      - JWT_REFRESH_SECRET=your_jwt_refresh_secret_key_here
    env_file:
      - ./srcs/auth/.env
    networks:
      - transcendence_network

  api-gateway:
    build:
      context: ./srcs/api_gateway
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - auth
    networks:
      - transcendence_network

  frontend:
    build:
      context: ./srcs/frontend
      dockerfile: Dockerfile
    networks:
      - transcendence_network

  web-nginx:
    build:
      context: ./srcs/web_nginx
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - frontend
    networks:
      - transcendence_network

networks:
  transcendence_network:
    driver: bridge