services:
  vault:
    image: hashicorp/vault:1.16
    container_name: vault
    environment:
      # Modo dev – NUNCA usar em produção!
      VAULT_DEV_ROOT_TOKEN_ID: # definir
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    cap_add:            # evita que o Vault seja swapado em disco
      - IPC_LOCK
    ports:
      - "8200:8200"     # UI / API do Vault

  api:
    build: .
    container_name: fastify-api
    environment:
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: # definir
      PORT: 3000
    depends_on:
      - vault
    ports:
      - "3000:3000"     # endpoints Fastify
