name: Auto PR for Hotfix Branches

on:
  push:
    branches:
      - 'hotfix/*'

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Pull Request to main
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ${{ github.ref_name }}
          title: 'Hotfix: ${{ github.ref_name }}'
          body: 'PR automático criado para aplicar hotfix na main.'
          draft: false 