name: Auto PR for Hotfix Branches

on:
  push:
    branches:
      - 'hotfix/*'

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request to main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_BRANCH: ${{ github.ref_name }}
        run: |
          curl -X POST -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d "{\"title\":\"Hotfix: $HEAD_BRANCH\",\"head\":\"$HEAD_BRANCH\",\"base\":\"main\",\"body\":\"PR automático criado para aplicar hotfix na main.\"}" 