name: Auto Release to Main

on:
  workflow_run:
    workflows: ["Auto Release PR for Feature Branches"]
    types:
      - completed

permissions:
  contents: write
  pull-requests: write

jobs:
  create-main-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest release branch
        id: get_release_branch
        run: |
          branch=$(git ls-remote --heads origin 'release-*' | awk '{print $2}' | sed 's/refs\/heads\///' | sort -V | tail -n1)
          echo "release_branch=$branch" >> $GITHUB_OUTPUT
          echo "Última release branch: $branch"

      - name: Extract version from branch name
        id: version
        run: |
          version=$(echo "${{ steps.get_release_branch.outputs.release_branch }}" | sed 's/release-//')
          echo "version=$version" >> $GITHUB_OUTPUT
          echo "Release version: $version"

      - name: Create Pull Request to main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HEAD_BRANCH: ${{ steps.get_release_branch.outputs.release_branch }}
          VERSION: ${{ steps.version.outputs.version }}
        run: |
          response=$(curl -s -X POST -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d "{\"title\":\"Release: $VERSION\",\"head\":\"$HEAD_BRANCH\",\"base\":\"main\",\"body\":\"PR automático criado para aplicar release $VERSION na main.\n\n**Release Branch:** $HEAD_BRANCH\n**Version:** $VERSION\n\nEste PR foi criado automaticamente."}")
          echo "$response"
          if echo "$response" | grep -q '"A pull request already exists"'; then
            echo "Já existe um PR aberto para esta branch. Nenhuma ação necessária."
            exit 0
          fi
          if ! echo "$response" | grep -q '"url"'; then
            echo "Erro ao criar o PR!"
            exit 1
          fi 