name: Block Non-Hotfix/Release PRs to Main

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Validate source branch and author
        id: validate
        run: |
          if [[ "$GITHUB_HEAD_REF" =~ ^hotfix\/.*$ || "$GITHUB_HEAD_REF" =~ ^release-[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            if [[ "$GITHUB_ACTOR" == "github-actions[bot]" ]]; then
              echo "autorizado=true" >> $GITHUB_OUTPUT
              exit 0
            fi
          fi
          echo "autorizado=false" >> $GITHUB_OUTPUT
          exit 1

      - name: Close unauthorized PR
        if: steps.validate.outputs.autorizado == 'false'
        uses: peter-evans/close-pull@v3
        with:
          pull-request-number: ${{ github.event.pull_request.number }}
          comment: |
            Este PR foi fechado automaticamente porque apenas PRs de branches hotfix/* ou release-X-X-X criados pelo workflow são permitidos para main. 